######################################################################
# Automatically generated by qmake (2.01a) ?? 19. ??? 18:36:57 2012
######################################################################

CONFIG+=qtestlib
TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += . \
    d:/Git/sui/sui/core \
    ../sc-store \
    ../sc-store/sc-machine/include
LIBS +=-L../bin -lsc-store
# Input
SOURCES += tst_testapptest.cpp

OBJECTS_DIR = obj

MOC_DIR = moc

DESTDIR = ../bin

